version: '3.3'
services:
  postgres:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_DB: news_parser
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: superpass
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    build:
      context: ./back
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  vue:
    build:
      context: ./front
    ports:
      - "8000:8000"
    depends_on:
      - fastapi

volumes:
  postgres_data:
