app:
  fast_api_port: 5000

db:
  type: postgresql
  connector: asyncpg
  host: localhost
  port: 5433
  login: postgres
  password: 020390
  name: wb_bot
  show_echo: no # if enable shows all SQL queries and results
  # performance settings:
#  pool_size: 20
#  max_overflow: 10
#  chunk_size: 1000


parser:
  parser_period_sec: 300