db:
  type: "postgresql"
  connector: "asyncpg"
  host_and_port: "postgres"
  name: "news_parser"
  login: "postgres"
  password: "superpass"
  show_echo: false # if enable shows all SQL queries and results


parser:
  parse_interval_sec: 300
  main_uri: "https://news.am/eng/"
  news_limit: 5