app:
  fast_api_port: 5000

db:
  type: "postgresql"
  connector: "asyncpg"
  url: "localhost:5432"
  name: "news_parser"
  login: "postgres"
  password: "superpass"
  show_echo: false # if enable shows all SQL queries and results


parser:
  parser_period_sec: 300