app:
  fast_api_port: 5000

db:
  type: "postgresql"
  connector: "asyncpg"
  host: "localhost"
  port: 5433
  login: "postgres"
  password: "80808080"
  name: "news_parser"
  show_echo: false # if enable shows all SQL queries and results
  # performance settings:
#  pool_size: 20
#  max_overflow: 10
#  chunk_size: 1000


parser:
  parser_period_sec: 300