version: 1
formatters:
  simple:
    format: "%(asctime)s.%(msecs)03d; %(levelname)s; %(processName)s; %(name)s; %(funcName)s=%(lineno)d; %(message)s"
  colored:
    (): colorlog.ColoredFormatter
    format: '%(asctime)s %(log_color)s[%(levelname)s] - module=%(name)s - %(name)s.%(funcName)s - %(blue)s%(message)s'
    datefmt: '%H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: colored
    stream: ext://sys.stdout
  parser_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: 'log/parser.log'
    maxBytes: 3145728
    backupCount: 5
    encoding: utf-8
  all_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: 'log/all.log'
    maxBytes: 10485760
    backupCount: 5
    encoding: utf-8

loggers:
  parser:
    level: DEBUG
    handlers: [ console, parser_file_handler ]
    propagate: False
root:
  level: DEBUG
  handlers: [ console, all_file_handler ]
disable_existing_loggers: no
